### ISSUE TITLE
Don't use tight requirements

### ISSUE THREAD

**Issue by hsnprsd** [AndreiDrang/python3-anticaptcha#66]
Hey.
As you may know python's new package dependency resolver is going to change and be strict about conflicting package dependencies.
The current requirements are too strict and I don't think they are needed.

**Comment by AndreiDrang** [comment]
Hi!
> As you may know python's new package dependency resolver
Nope, I don't know. Can u give more info?

**Comment by hsnprsd** [comment]
You can see the documentation here: https://pip.pypa.io/en/latest/user_guide/#changes-to-the-pip-dependency-resolver-in-20-3-2020

**Comment by hatarist** [comment]
Anyway, the strict version pinning has lead to a problem where you can't upgrade the aiohttp from 3.7.2 to 3.7.3 because this module explicitly asks for 3.7.2 (in setup.py).

Anyway, it's a good practice to use `>=` and `<=` instead of just using the certain version `==`.
Which minimum version of the aiohttp does python3-anticaptcha really need?

(so we could change it to, say, `aiohttp>=3.0.0` to get broader coverage of compatible envrionments)

**Comment by AndreiDrang** [comment]
Check pls https://github.com/AndreiDrang/python3-anticaptcha/pull/68
